[general]
working_directory = "C:\\Users\\itterum"
import = [ "~/AppData/Roaming/alacritty/kanagawa-wave.toml" ]

[window]
dynamic_title = false
dynamic_padding = true
opacity = 0.9

  [window.dimensions]
  columns = 130
  lines = 45

  [window.padding]
  x = 12
  y = 12

[font]
size = 10
builtin_box_drawing = true

  [font.normal]
  family = "FiraCode Nerd Font"
  style = "Regular"

  [font.bold]
  family = "FiraCode Nerd Font"
  style = "Bold"

  [font.italic]
  family = "FiraCode Nerd Font"
  style = "Italic"

[terminal.shell]
program = "pwsh.exe"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
